version: "3.7"

services: 
  backend:
    image: bolk9652/backend:0.0.7
    ports: 
      - 80:8000
    secrets:
      - ALLOWED_HOSTS
      - AZURE_ACCOUNT_KEY
      - AZURE_ACCOUNT_NAME
      - DJANGO_POSTGRESQL_URL
      - DJANGO_SECRET_KEY
      - JWT_SECRET_KEY
      - CORS_ALLOWED_ORIGINS

secrets:
  AZURE_ACCOUNT_KEY:
    external: true
  AZURE_ACCOUNT_NAME:
    external: true
  DJANGO_POSTGRESQL_URL:
    external: true
  DJANGO_SECRET_KEY:
    external: true
  JWT_SECRET_KEY:
    external: true
  ALLOWED_HOSTS:
    external: true
  CORS_ALLOWED_ORIGINS:
    external: true