# Generated by Django 3.1.5 on 2021-01-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20210108_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, unique=True, verbose_name='닉네임'),
        ),
    ]
