# Generated by Django 3.1.5 on 2021-01-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='fdsa', upload_to='instagram/post/%Y/%m/%d', verbose_name='사진'),
            preserve_default=False,
        ),
    ]
